#!/bin/sh

STAGED_FILES=$(git diff --cached --name-only)

npm run precommit
if [ $? -ne 0 ]; then
  exit 1
fi

for file in $STAGED_FILES; do
  if [ -f "$file" ]; then
    git add -f "$file"
  fi
done
